export enum AccessType {
  PERMANENT = 'PERMANENT',
  TEMPORARY = 'TEMPORARY',
  VISITOR = 'VISITOR',
  CONTRACTOR = 'CONTRACTOR',
  EMERGENCY = 'EMERGENCY',
  MAINTENANCE = 'MAINTENANCE'
}

export enum AccessStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING'
}

export enum AccessMethod {
  PIN = 'PIN',
  CARD = 'CARD',
  BIOMETRIC = 'BIOMETRIC',
  MOBILE = 'MOBILE',
  FACIAL = 'FACIAL',
  EMERGENCY = 'EMERGENCY',
  MANUAL = 'MANUAL'
}

export enum AccessResult {
  SUCCESS = 'SUCCESS',
  DENIED = 'DENIED',
  EXPIRED = 'EXPIRED',
  INVALID_PIN = 'INVALID_PIN',
  INVALID_CARD = 'INVALID_CARD',
  INVALID_BIOMETRIC = 'INVALID_BIOMETRIC',
  OUTSIDE_SCHEDULE = 'OUTSIDE_SCHEDULE',
  DOOR_OFFLINE = 'DOOR_OFFLINE',
  ANTI_PASSBACK = 'ANTI_PASSBACK',
  MAX_USAGE_REACHED = 'MAX_USAGE_REACHED',
  EMERGENCY = 'EMERGENCY',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}