export enum AccessPermission {
  // Basic permissions
  ENTER = 'ENTER',
  EXIT = 'EXIT',
  
  // Time-based permissions
  AFTER_HOURS = 'AFTER_HOURS',
  WEEKEND = 'WEEKEND',
  HOLIDAY = 'HOLIDAY',
  
  // Special area permissions
  RESTRICTED_AREA = 'RESTRICTED_AREA',
  SERVER_ROOM = 'SERVER_ROOM',
  EXECUTIVE_FLOOR = 'EXECUTIVE_FLOOR',
  PARKING = 'PARKING',
  
  // Override permissions
  OVERRIDE_SCHEDULE = 'OVERRIDE_SCHEDULE',
  OVERRIDE_OCCUPANCY = 'OVERRIDE_OCCUPANCY',
  EMERGENCY_ACCESS = 'EMERGENCY_ACCESS',
  
  // Management permissions
  GRANT_TEMPORARY_ACCESS = 'GRANT_TEMPORARY_ACCESS',
  MANAGE_VISITORS = 'MANAGE_VISITORS',
  VIEW_ACCESS_LOGS = 'VIEW_ACCESS_LOGS',
  MANAGE_DOORS = 'MANAGE_DOORS'
}