export enum DoorStatus {
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
  EMERGENCY = 'EMERGENCY'
}

export enum DoorType {
  MAIN_ENTRANCE = 'MAIN_ENTRANCE',
  SIDE_ENTRANCE = 'SIDE_ENTRANCE',
  EMERGENCY_EXIT = 'EMERGENCY_EXIT',
  INTERNAL = 'INTERNAL',
  ELEVATOR = 'ELEVATOR',
  PARKING = 'PARKING',
  RESTRICTED = 'RESTRICTED'
}

export enum LockType {
  ELECTRONIC = 'ELECTRONIC',
  MAGNETIC = 'MAGNETIC',
  MECHANICAL = 'MECHANICAL',
  BIOMETRIC = 'BIOMETRIC',
  HYBRID = 'HYBRID'
}