export enum VisitorStatus {
  SCHEDULED = 'SCHEDULED',
  PRE_REGISTERED = 'PRE_REGISTERED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}

export enum VisitorType {
  GUEST = 'GUEST',
  CONTRACTOR = 'CONTRACTOR',
  DELIVERY = 'DELIVERY',
  INTERVIEW = 'INTERVIEW',
  VENDOR = 'VENDOR',
  MAINTENANCE = 'MAINTENANCE',
  GOVERNMENT = 'GOVERNMENT',
  OTHER = 'OTHER'
}