apiVersion: v1
kind: Secret
metadata:
  name: forten-secrets
  namespace: forten
type: Opaque
data:
  # Base64 encoded values
  # Use: echo -n "your-value" | base64
  
  # Database
  postgres-user: Zm9ydGVu  # forten
  postgres-password: ""  # YOUR_BASE64_ENCODED_PASSWORD
  redis-password: ""     # YOUR_BASE64_ENCODED_PASSWORD
  rabbitmq-user: Zm9ydGVu  # forten
  rabbitmq-password: ""  # YOUR_BASE64_ENCODED_PASSWORD
  
  # JWT
  jwt-secret: ""         # YOUR_BASE64_ENCODED_JWT_SECRET
  jwt-refresh-secret: "" # YOUR_BASE64_ENCODED_REFRESH_SECRET
  
  # URLs
  redis-url: ""          # redis://:password@redis:6379
  postgres-url: ""       # postgresql://forten:password@postgres:5432/forten_db
  rabbitmq-url: ""       # amqp://forten:password@rabbitmq:5672
  
  # External Services
  hikcentral-api-key: ""    # YOUR_BASE64_ENCODED_HIKCENTRAL_KEY
  qbox-api-key: ""          # YOUR_BASE64_ENCODED_QBOX_KEY
  twilio-account-sid: ""    # YOUR_BASE64_ENCODED_TWILIO_SID
  twilio-auth-token: ""     # YOUR_BASE64_ENCODED_TWILIO_TOKEN
  sendgrid-api-key: ""      # YOUR_BASE64_ENCODED_SENDGRID_KEY
  firebase-private-key: ""  # YOUR_BASE64_ENCODED_FIREBASE_KEY
  
  # Email
  email-smtp-user: ""    # YOUR_BASE64_ENCODED_EMAIL
  email-smtp-pass: ""    # YOUR_BASE64_ENCODED_EMAIL_PASSWORD

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forten-config
  namespace: forten
data:
  # Non-sensitive configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  HIKCENTRAL_API_URL: "https://api.hikcentral.com"
  QBOX_API_URL: "https://api.qbox.com"
  EMAIL_SMTP_HOST: "smtp.gmail.com"
  EMAIL_SMTP_PORT: "587"
  TWILIO_WHATSAPP_NUMBER: "whatsapp:+1234567890"
  FIREBASE_PROJECT_ID: "your-firebase-project-id"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-xxx@your-project.iam.gserviceaccount.com"
  RATE_LIMIT_MAX: "1000"
  RATE_LIMIT_WINDOW: "900000"